permissions:
  contents: write

name: .NET

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore SharePointMirror/

      - name: Build
        run: dotnet build --configuration Release --no-restore SharePointMirror/

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal SharePointMirror/

      - name: Publish Linux self-contained
        id: publish-linux-sc
        run: |
          out=publish/linux-selfcontained
          dotnet publish SharePointMirror/ -c Release -r linux-x64 --self-contained true -o "$out"
          tar -czf "$out.tar.gz" -C "$(dirname "$out")" "$(basename "$out")"
          echo "artifact-path=$out.tar.gz" >> "$GITHUB_OUTPUT"

      - name: Publish Windows self-contained
        id: publish-windows-sc
        run: |
          out=publish/windows-selfcontained
          dotnet publish SharePointMirror/ -c Release -r win-x64 --self-contained true -o "$out"
          zip -r "$out.zip" "$out"
          echo "artifact-path=$out.zip" >> "$GITHUB_OUTPUT"

      - name: Publish Linux framework-dependent
        id: publish-linux-fd
        run: |
          out=publish/linux-net8.0
          dotnet publish SharePointMirror/ -c Release -r linux-x64 --self-contained false -o "$out"
          tar -czf "$out.tar.gz" -C "$(dirname "$out")" "$(basename "$out")"
          echo "artifact-path=$out.tar.gz" >> "$GITHUB_OUTPUT"

      - name: Publish Windows framework-dependent
        id: publish-windows-fd
        run: |
          out=publish/windows-net8.0
          dotnet publish SharePointMirror/ -c Release -r win-x64 --self-contained false -o "$out"
          zip -r "$out.zip" "$out"
          echo "artifact-path=$out.zip" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux self-contained
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: publish/linux-selfcontained.tar.gz
          asset_name: linux-selfcontained.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows self-contained
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: publish/windows-selfcontained.zip
          asset_name: windows-selfcontained.zip
          asset_content_type: application/zip

      - name: Upload Linux framework-dependent
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: publish/linux-net8.0.tar.gz
          asset_name: linux-net8.0.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows framework-dependent
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: publish/windows-net8.0.zip
          asset_name: windows-net8.0.zip
          asset_content_type: application/zip
